Add Vortex Network
LunarClient/ServerMappings pull request #109
Opened 2021-12-27 17:23 UTC by charlesvien

2021-12-27 23:08 UTC, GrowlyX requested changes

2021-12-27 23:08 UTC, GrowlyX commented on servers.json
> +            "mc.vortexnetwork.net"
You do not need to add sub-domains to this array, Lunar Client services already detect them.

2021-12-30 18:15 UTC, GrowlyX submitted a review, later dismissed

2022-01-02 05:20 UTC, ThatKawaiiSam submitted a review, later dismissed

2022-01-12 14:56 UTC, GrowlyX commented
![image](https://user-images.githubusercontent.com/62861393/149164236-109b1f2a-dfc4-4d05-b08a-572018ed7317.png)
Could you resolve this? @charlesvien

2022-01-18 15:57 UTC, GrowlyX commented
> ![image](https://user-images.githubusercontent.com/62861393/149164236-109b1f2a-dfc4-4d05-b08a-572018ed7317.png) Could you resolve this? @charlesvien

@charlesvien

2022-01-19 15:47 UTC, GrowlyX commented
Closing due to inactivity- feel free to create a new PR when you're back

2022-01-19 15:47 UTC, closed without merging