MineCreators
LunarClient/ServerMappings pull request #1274
Opened 2023-12-11 17:32 UTC by SpuckyYT123

MineCreators is a vibrant Discord server dedicated to content creators that has taken an exciting step in expanding its community into the Minecraft universe. In an effort to offer players unique experiences, we have introduced an exciting Bedwars mode. We're committed to providing an inclusive and fun space for the Minecraft community, and we won't stop there. In the near future, we plan to add other exciting modalities such as BoxPvP and Skywars to provide our members with a variety of challenges and thrills. Join MineCreators and be part of a community that is constantly growing and evolving. The adventure is just beginning!

2023-12-11 22:10 UTC, Anakinnnnn requested changes
You need to remove the logo and background from the main directory

2023-12-12 10:13 UTC, SpuckyYT123 reviewed
Removed logo.png & background.png.
Added servers/minecreators/background.png
Added servers/minecreators/logo.png

2023-12-17 07:49 UTC, Anakinnnnn requested changes
I tried to help, please fix the rest.

2023-12-17 20:57 UTC, JackwithC2 commented
![background](https://github.com/LunarClient/ServerMappings/assets/86273091/4eb39a5d-8c55-4235-a913-04ee28176e3a)
The background.png is 760x428 should be 1920x1080 i believe

2023-12-17 21:19 UTC, JackwithC2 commented
https://github.com/LunarClient/ServerMappings/pull/1297

2023-12-18 11:56 UTC, closed without merging