Add MadNetwork
LunarClient/ServerMappings pull request #133
Opened 2022-01-02 17:37 UTC by Lucanius69

2022-01-02 19:12 UTC, GrowlyX requested changes

2022-01-02 19:12 UTC, GrowlyX commented on servers.json
> +            "play.madnetwork.club"
Lunar Client services automatically detect sub-domains, please remove this.

2022-01-02 19:18 UTC, GrowlyX approved these changes

2022-01-02 19:18 UTC, GrowlyX approved these changes

2022-01-03 16:29 UTC, Lucanius69 commented
When is it going to be uploaded if I may ask?

2022-01-03 16:32 UTC, merged