Add MoonsideMC
LunarClient/ServerMappings pull request #143
Opened 2022-01-07 05:52 UTC by themaggiesgamers

![Moonside](https://user-images.githubusercontent.com/32754218/148498485-0b8a0e56-3757-4186-bc0a-69fa86066bfc.png)

2022-01-09 18:23 UTC, GoldenEdit requested changes
Your 'id' and image name do not match. Please make them the same.

2022-01-10 11:23 UTC, GoldenEdit submitted a review, later dismissed

2022-01-12 14:52 UTC, GrowlyX submitted a review, later dismissed

2022-01-12 14:52 UTC, GrowlyX commented
Thanks, @GoldenEdit !

2022-01-12 14:53 UTC, GrowlyX approved these changes

2022-01-12 14:54 UTC, merged