add another domain to pvparcade
LunarClient/ServerMappings pull request #150
Opened 2022-01-11 21:03 UTC by freaky767

2022-01-12 14:49 UTC, GrowlyX requested changes

2022-01-12 14:49 UTC, GrowlyX commented on servers.json
>              "pvparcade.gg"
You forgot a comma here

2022-01-14 15:40 UTC, freaky767 commented on servers.json
>              "pvparcade.gg"
fixed?

2022-01-14 15:58 UTC, GrowlyX approved these changes

2022-01-14 15:59 UTC, merged