Added Voidedcraft Bedwars
LunarClient/ServerMappings pull request #179
Opened 2022-02-01 14:10 UTC by OmriOn

### General:

* [ ] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:

* [ ] My formatting matches the pre-existing formatting.
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping with my id.
* [ ] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string *(ex. `myserver`)*
  - [ ] `name`: a string *(ex. `MyServerPvP`)*
  - [ ] `addresses`: an array with lowercase strings *(ex. of address `my.server`)*
    - You do not need to specify sub-domains, Lunar Client services automatically detect them.

### Logo Additions or Updates:

* [ ] My image is a `.png` file.
* [ ] I uploaded the image in the `logos` directory.
* [ ] My image is transparent & square (1:1 aspect ratio).
* [ ] My image is a minimum of `512` pixels in width and height.
* [ ] My images image name matches its mapping id.

- [ "]

2022-02-03 23:03 UTC, GrowlyX commented
what in the world

2022-02-03 23:04 UTC, GrowlyX requested changes

2022-02-03 23:04 UTC, GrowlyX commented on servers.json
> +		             VoidedCraft.mcalias.com
this formatting is **EXTREMELY** incorrect

please learn JSON

2022-02-04 00:25 UTC, GrowlyX approved these changes

2022-02-04 00:26 UTC, GrowlyX approved these changes

2022-02-04 00:27 UTC, GrowlyX approved these changes

2022-02-04 00:28 UTC, merged

2022-02-04 10:20 UTC, OmriOn commented
I don't know JSON ok?