Add ValleyPvP Network
LunarClient/ServerMappings pull request #206
Opened 2022-02-28 21:26 UTC by ByJoako

### General:

* [ ] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:

* [ ] My formatting matches the pre-existing formatting.
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping with my id.
* [ ] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string *(ex. `myserver`)*
  - [ ] `name`: a string *(ex. `MyServerPvP`)*
  - [ ] `addresses`: an array with lowercase strings *(ex. of address `my.server`)*
    - You do not need to specify sub-domains, Lunar Client services automatically detect them.

### Logo Additions or Updates:

* [ ] My image is a `.png` file.
* [ ] I uploaded the image in the `logos` directory.
* [ ] My image is transparent & square (1:1 aspect ratio).
* [ ] My image is a minimum of `512` pixels in width and height.
* [ ] My images image name matches its mapping id.

2022-03-01 21:46 UTC, GrowlyX submitted a review, later dismissed

2022-03-01 21:46 UTC, GrowlyX commented
@ByJoako, please resolve these conflicts:
![image](https://user-images.githubusercontent.com/62861393/156254309-be8904cb-e235-4c32-b640-9d1b8d522f6b.png)

2022-03-02 02:59 UTC, ByJoako commented
I think it was solved

2022-03-02 16:08 UTC, GrowlyX approved these changes

2022-03-02 16:09 UTC, GrowlyX requested changes

2022-03-02 16:09 UTC, GrowlyX commented on servers.json
> +
Could you remove this indent for me?

2022-03-02 16:09 UTC, GrowlyX commented on servers.json
> +
This one as well

2022-03-03 17:44 UTC, GrowlyX approved these changes

2022-03-03 17:44 UTC, GrowlyX commented
Thanks!

2022-03-03 17:44 UTC, merged