Added Esta Network
LunarClient/ServerMappings pull request #240
Opened 2022-03-21 22:52 UTC by tdvne

2022-03-22 02:36 UTC, GrowlyX requested changes

2022-03-22 02:36 UTC, GrowlyX commented on servers.json
> +            "bypass.esta.land"
You do not need to specify sub domains.

2022-03-22 02:36 UTC, GrowlyX commented on servers.json
> +        "id": "esta",
Your logo file name must match the id.

2022-03-22 20:21 UTC, tdvne commented on servers.json
> +        "id": "esta",
> Your logo file name must match the id.

Changes have been made.

2022-03-23 02:06 UTC, GrowlyX approved these changes

2022-03-24 12:14 UTC, merged