Added Eclipsepvp
LunarClient/ServerMappings pull request #315
Opened 2022-04-22 18:35 UTC by JuanSeeee

### General:
* [ ] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [ ] No changes were made to the file's formatting.
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping matching my id.
* [ ] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string *(ex. `myserver`)*
  - [ ] `name`: a string *(ex. `MyServerPvP`)*
  - [ ] `addresses`: an array with lowercase strings *(ex. of address `my.server`)*
    - You do not need to specify sub-domains, Lunar Client services automatically detect them.

### Logo Additions or Updates:
* [ ] My image is a `png` file.
* [ ] I uploaded my image to the `logos` directory.
* [ ] My image has a transparent background and is square (1:1 aspect ratio).
* [ ] My image is `512` pixels in width and height.
* [ ] My image's file name matches its mapping id.

2022-04-23 18:22 UTC, jacobk999 requested changes

2022-04-23 18:22 UTC, jacobk999 commented on servers.json
> +        "id" : "Eclipsepvp" ,
The `id` field should be lowercase. You are also missing your server logo in the `logos` directory

2022-04-23 22:50 UTC, GrowlyX requested changes
I don't think the other reviewers noticed this, but your field keys must be in English, matching the existing mappings.

Please change:
 - `nombre` -> `name`
 - `direcciones` -> `addresses`

2022-04-26 16:41 UTC, GrowlyX requested changes

2022-04-26 16:41 UTC, GrowlyX commented on servers.json
>          "id" : "eclipsepvp",
Could you also remove the unnecessary whitespaces after the field names?

2022-04-27 16:17 UTC, GrowlyX submitted a review, later dismissed

2022-04-27 16:19 UTC, GrowlyX approved these changes

2022-04-27 16:20 UTC, GrowlyX commented
Your server logo is still missing.

2022-04-29 18:08 UTC, jacobk999 commented
Closed for inactivity.

2022-04-29 18:08 UTC, closed without merging