Add SplitUHC
LunarClient/ServerMappings pull request #370
Opened 2022-06-04 19:53 UTC by AjuMeX

### General:
* [ ] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [ ] No changes were made to the file's formatting.
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping matching my id.
* [ ] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string *(ex. `myserver`)*
  - [ ] `name`: a string *(ex. `MyServerPvP`)*
  - [ ] `addresses`: an array with lowercase strings *(ex. of address `my.server`)*
    - You do not need to specify sub-domains, Lunar Client services automatically detect them.

### Logo Additions or Updates:
* [ ] My image is a `png` file.
* [ ] I uploaded my image to the `logos` directory.
* [ ] My image has a transparent background and is square (1:1 aspect ratio).
* [ ] My image is `512` pixels in width and height.
* [ ] My image's file name matches its mapping id.

2022-06-04 23:27 UTC, jacobk999 requested changes
Make this a png

2022-06-05 15:31 UTC, AjuMeX commented
> Make this a png

Ready 👍

2022-06-24 01:05 UTC, jacobk999 requested changes

2022-06-24 01:05 UTC, jacobk999 commented on servers.json
> +        "id": "split",
```suggestion
        "id": "splituhc",
```

2022-06-24 01:05 UTC, jacobk999 commented on servers.json
> +        ]
```suggestion
        "addresses": [
	    "splituhc.tk"
        ]
```

2022-06-24 01:07 UTC, jacobk999 requested changes

2022-06-24 01:07 UTC, jacobk999 commented on servers.json
> +    },
Your server logo is not a real `png`.

2022-07-31 14:35 UTC, GrowlyX requested changes

2022-07-31 14:35 UTC, GrowlyX commented on servers.json
> +	{
Please remove this indentation.

2022-08-04 17:53 UTC, closed without merging