Added 2 additional servers
LunarClient/ServerMappings pull request #38
Opened 2021-11-21 12:19 UTC by DanielCrewe

Added Fyre Network & MineKings Network

2021-11-22 16:15 UTC, GrowlyX commented on servers.json
> +            "play.fyre.cc"
Please take a look at:
[the ip-address section in the README](https://github.com/LunarClient/ServerMappings/blob/master/README.md#ip-addresses)

You do not need to add sub-domains to the addresses array.

2021-11-22 16:15 UTC, GrowlyX commented on servers.json
> +            "play.minekings.org",
Please remove these as well

2021-11-22 16:17 UTC, GrowlyX requested changes
Remove the un-needed subdomains in the `fyre` and `minekings` entries

2021-11-23 22:30 UTC, closed without merging

2021-11-23 22:36 UTC, DanielCrewe commented
Hey, considering I removed the GitHub repository from my GitHub account I have proposed another pull request, thanks.