Added Imperial.rip
LunarClient/ServerMappings pull request #397
Opened 2022-06-25 22:20 UTC by Jordanllc

### General:
* [ ] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [ ] No changes were made to the file's formatting.
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping matching my id.
* [ ] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string *(ex. `myserver`)*
  - [ ] `name`: a string *(ex. `MyServerPvP`)*
  - [ ] `addresses`: an array with lowercase strings *(ex. of address `my.server`)*
    - You do not need to specify sub-domains, Lunar Client services automatically detect them.

### Logo Additions or Updates:
* [ ] My image is a `png` file.
* [ ] I uploaded my image to the `logos` directory.
* [ ] My image has a transparent background and is square (1:1 aspect ratio).
* [ ] My image is `512` pixels in width and height.
* [ ] My image's file name matches its mapping id.

2022-07-29 21:30 UTC, GrowlyX requested changes

2022-07-29 21:30 UTC, GrowlyX commented on servers.json
> +        "id": "imperialrip",
You must rename/attach your server logo file.

2022-07-29 21:30 UTC, GrowlyX commented on servers.json
> +
Remove this blank line.

2022-07-30 20:05 UTC, imconnorngl commented
The server JSON is not formatted correctly.

This PR has also been inactive for over a week so I have closed it.
If you still would like to add your server please make a new PR following the guidelines which can be found in the [README](https://github.com/LunarClient/ServerMappings).

2022-07-30 20:05 UTC, closed without merging