Added ComuGamers Network
LunarClient/ServerMappings pull request #406
Opened 2022-07-03 22:11 UTC by Jojo1542

### General:
* [ ] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [ ] No changes were made to the file's formatting.
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping matching my id.
* [ ] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string *(ex. `myserver`)*
  - [ ] `name`: a string *(ex. `MyServerPvP`)*
  - [ ] `addresses`: an array with lowercase strings *(ex. of address `my.server`)*
    - You do not need to specify sub-domains, Lunar Client services automatically detect them.

### Logo Additions or Updates:
* [ ] My image is a `png` file.
* [ ] I uploaded my image to the `logos` directory.
* [ ] My image has a transparent background and is square (1:1 aspect ratio).
* [ ] My image is `512` pixels in width and height.
* [ ] My image's file name matches its mapping id.

PD: My logo is actually on the repo: https://github.com/LunarClient/ServerMappings/blob/master/logos/comugamers.png but my server got removed because i missed the id and i put "comugamrs" not comugamers.

2022-07-07 22:09 UTC, GrowlyX requested changes
Please add your server logo.

2022-07-08 02:28 UTC, Jojo1542 commented
> Please add your server logo.

My server logo is actually on the original repo, you can check it on the upper link

2022-07-29 21:23 UTC, GrowlyX commented
> > Please add your server logo.
> 
> My server logo is already on the repository, you can actually see it [here](https://github.com/LunarClient/ServerMappings/blob/2a4abd8a06ff2b1b4c3c144c8178c59aba88b4d4/logos/comugamers.png) (or just look up `comugamers.png` on the `logos` folder).
> 
> My server was only removed because I didn't have a logo due to the ID having a typo (`comugamrs` instead of `comugamers`).

Thank you, and sorry for the late response.

2022-07-29 21:23 UTC, GrowlyX approved these changes

2022-07-29 21:23 UTC, merged