Added NeptuneMC Network
LunarClient/ServerMappings pull request #427
Opened 2022-07-26 18:54 UTC by thekingdmb

### General:
* [ ] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [ ] No changes were made to the file's formatting.
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping matching my id.
* [ ] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string *(ex. `myserver`)*
  - [ ] `name`: a string *(ex. `MyServerPvP`)*
  - [ ] `addresses`: an array with lowercase strings *(ex. of address `my.server`)*
    - You do not need to specify sub-domains, Lunar Client services automatically detect them.

### Logo Additions or Updates:
* [ ] My image is a `png` file.
* [ ] I uploaded my image to the `logos` directory.
* [ ] My image has a transparent background and is square (1:1 aspect ratio).
* [ ] My image is `512` pixels in width and height.
* [ ] My image's file name matches its mapping id.

2022-07-26 18:58 UTC, thekingdmb commented
PNG on 512x51
![neptunemc512](https://user-images.githubusercontent.com/83374617/181089585-89c482e7-0370-4b9c-a188-4db9cd695ffc.png)
2

2022-07-29 20:08 UTC, SrIzan10 requested changes
and... the ip?

2022-07-29 21:02 UTC, GrowlyX requested changes

2022-07-29 21:02 UTC, GrowlyX commented on servers.json
> +            "neptunemc"
This is an invalid address.

2022-07-29 21:29 UTC, SrIzan10 commented on servers.json
> +            "neptunemc"
yeah i agree

2022-07-31 01:22 UTC, thekingdmb commented on servers.json
> +            "neptunemc"
Oops, srry it's neptunemc.es

2022-07-31 01:26 UTC, thekingdmb commented on servers.json
> +            "neptunemc"
Updated tho

2022-07-31 19:10 UTC, SrIzan10 submitted a review, later dismissed
fair enough

2022-07-31 19:15 UTC, itsJordan requested changes
Please include the following properties into your servers.json:

primaryAddress
minecraftVersions
primaryMinecraftVersion

Consult the updated README for more information.

2022-07-31 21:06 UTC, thekingdmb commented
Added on the server.json
primaryAddress
minecraftVersions
primaryMinecraftVersion

2022-07-31 21:43 UTC, itsJordan requested changes
Please adjust your 'minecraftVersions' field to match the available options correctly:
"1.7", "1.8", "1.12", "1.16", "1.17", "1.18", "1.19"

2022-07-31 22:15 UTC, itsJordan approved these changes

2022-07-31 22:15 UTC, itsJordan approved these changes

2022-07-31 22:17 UTC, merged