Added Myntora
LunarClient/ServerMappings pull request #445
Opened 2022-08-05 21:35 UTC by RyanMoodGAMING

### General:
* [x] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated servers.json`)*
* [x] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [x] No changes were made to the file's formatting.
* [x] There are no syntax errors.
* [x] There is no pre-existing mapping matching my id.
* [x] My field values match your requirements.
* You can view our patterns here: [servers.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/servers.schema.json), or take a look below and complete the field checklist:
  - [x] `id`: a lowercase string *(ex. `myserver`)*
  - [x] `name`: a string *(ex. `MyServerPvP`)*
  - [x] `addresses`: an array with lowercase strings *(ex. `["my.server", "your-server.com"]`)*
    - You do not need to specify subdomains, Lunar Client services automatically detect them.
  - [x] `primaryAddress`: an address *(ex. `my.server`)*
  - [x] `minecraftVersions`: an array with Minecraft versions as strings *(ex. `["1.18", "1.19"]`)*
  - [x] `primaryMinecraftVersion`: a Minecraft version as a string *(ex. `1.18`)*

### Logo Additions or Updates:
* [ ] My image is a `png` file.
* [ ] I uploaded my image to the `logos` directory.
* [ ] My image has a transparent background and is square (1:1 aspect ratio).
* [ ] My image is `512` pixels in width and height.
* [ ] My image's file name matches its mapping id.

2022-08-05 21:47 UTC, itsJordan commented on servers.json
> +            "play.myntora.net"
```suggestion
            "myntora.net"
```

2022-08-05 21:48 UTC, itsJordan requested changes
Please add your server logo to the 'logos' directory

2022-08-05 23:35 UTC, RyanMoodGAMING commented
Will do once I’ve been sent to them.

2022-08-12 16:32 UTC, itsJordan commented
> Will do once I’ve been sent to them.

Do you have any idea when you will have access to the logo?

2022-08-12 20:08 UTC, RyanMoodGAMING commented
Uploaded.

2022-08-12 20:32 UTC, itsJordan commented on servers.json
>      }
```suggestion
    },
```

2022-08-12 20:33 UTC, itsJordan requested changes
Please review my suggestion to validate your json.

2022-08-12 20:34 UTC, RyanMoodGAMING commented
Suggestion added.

2022-08-13 21:48 UTC, itsJordan commented on servers.json
> +        "minecraftVersions": ["1.8", "1.9", "1.12", "1.16", "1.18", "1.19"],
```suggestion
        "minecraftVersions": ["1.8", "1.12", "1.16", "1.18", "1.19"],
```

2022-08-13 21:48 UTC, itsJordan requested changes
1.9 is not supported on Lunar.

2022-08-13 22:56 UTC, RyanMoodGAMING commented
My bad, I thought it meant versions supported in general not lunar versions.

2022-08-13 22:57 UTC, itsJordan approved these changes

2022-08-13 22:57 UTC, merged