Fix Sunrise City Server
LunarClient/ServerMappings pull request #481
Opened 2022-08-27 12:18 UTC by JustSkeppYT

### General:
* [ ] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated metadata.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [ ] Folder with appropriate name has been created / updated (must not include any non-alpha characters or whitespace).
* [ ] No changes were made to the file's formatting (4 spaces per tab).
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping matching my id (check if there is an existing folder).
* [ ] My field values match your requirements.
* You can view our patterns here: [metadata.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/metadata.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string, which should match the folder name *(ex. `myserver`)*
  - [ ] `name`: a string *(ex. `MyServerPvP`)*
  - [ ] `addresses`: an array with lowercase strings *(ex. `["my.server", "your-server.com"]`)*
    - You do not need to specify subdomains, Lunar Client services automatically detect them.
  - [ ] `primaryAddress`: an address *(ex. `my.server`)*
  - [ ] `minecraftVersions`: an array with Minecraft versions as strings *(ex. `["1.18", "1.19"]` - Must be versions supported by Lunar Client)*
  - [ ] `primaryMinecraftVersion`: a Minecraft version as a string *(ex. `1.18` - Must be versions supported by Lunar Client)*
  - [ ] `primaryColor`: a hexademical color code that primarily distiguishes the server *(ex. `#00FFFF`)* 
  - [ ] `secondaryColor`: a hexademical color code that accompanies the `primaryColor` of the server *(ex. `#FF0000`)*
  - [ ] `primaryRegion`: the primary region where your server operates in *(ex. `NA`)*
  - [ ] `regions`: a list of regions where you have servers located that service your players *(ex. `["NA", "EU", "AS"]`)*
  - [ ] `gameTypes`: a list of games that describe the content on your server, must be a max of 3 listed *(ez. `["PVP", "UHC", "HCF"]`)*

### Media:
#### Logo
* [ ] My logo is a `png` file.
* [ ] I have uploaded my logo to my server folder *(ex. `lunarnetwork`)* and named it `logo.png`.
* [ ] My logo has a transparent background and is square (1:1 aspect ratio).
* [ ] My logo is `512` pixels in width and height.
* [ ] My logo is my own property and complies with relevant copyright/privacy laws.

#### Background
* [ ] My background is a `png` file.
* [ ] I have uploaded my background to my server folder *(ex. `lunarnetwork`)* and named it `background.png`.
* [ ] My background has an aspect ratio of 16:9.
* [ ] My background is atleast `1920` pixels in width and `1080` pixels in height (can be bigger, but must remain the same aspect ratio).
* [ ] My background contains relevant content pertaining to the server, is my own property, and complies with relevant copyright/privacy laws.

2022-08-27 12:19 UTC, JustSkeppYT commented
This commit is to update the old server details (sunrisecity) to add in a port.

2022-08-27 12:21 UTC, itsJordan requested changes
There are now new requirements for ServerMappings updates/submissions.

Please review the README and include all missing information.

2022-08-27 12:38 UTC, JustSkeppYT commented
Updated as per following the README.

2022-08-27 12:54 UTC, itsJordan requested changes
You are still missing the following:

- primaryLanguage
- languages
- primaryRegion
- regions
- gameTypes

2022-08-27 14:24 UTC, JustSkeppYT commented
> * gameTypes

How does gameTypes work, RPG?

2022-08-28 01:45 UTC, itsJordan requested changes
I cannot approve this PR as Lunar Client does not support ServerMappings with specified ports, and we cannot map this IP Address to a server as the server is not consistent.

Could you either:
1. Obtain a dedicated IP Address that your domain can be pointed at.
2. Configure an SRV record within your DNS configuration that points to your specific port:

Example:
- type: SRV Record

- value: _minecraft
- protocol: _tcp.play
- priority: 0
- weight: 5
- port: 2260
- target: play.sunrisecity.uk
- ttl: default/auto

2022-08-28 11:19 UTC, JustSkeppYT commented
Hmm, everything on that list is correct to our SRV already, not really sure why it doesn't work.
![image](https://user-images.githubusercontent.com/68767065/187071453-190b8c22-c7fb-4bf8-a774-1b8cee626528.png)

2022-08-28 11:23 UTC, JustSkeppYT commented
Does lunar client automatically forward the person into port 25565? That may be an issue.

2022-08-28 11:55 UTC, itsJordan commented
> Does lunar client automatically forward the person into port 25565? That may be an issue.

Lunar will direct the player to 25565 by default, but will direct connections to an alternate port if an SRV record exists just like vanilla.

Your SRV record is resolving fine for me (see img) and I can connect to the server using 'play.sunrisecity.uk' 
![image](https://user-images.githubusercontent.com/9994312/187072903-10e7fb80-66b2-4d39-9c66-090868ff7192.png)

Are you sure players are not consistently being connected to the correct place?

2022-08-28 11:58 UTC, JustSkeppYT commented
> Are you sure players are not consistently being connected to the correct place?

I'm not really sure what that means

2022-08-28 12:12 UTC, itsJordan commented
> > Are you sure players are not consistently being connected to the correct place?
> 
> I'm not really sure what that means

When I originally queried your reason for using a specific port, you responded with:

"
Yeah and anyways fort he Port 2260, the server sometimes redirect them to another server if we don't use port 2260.
Since due to the fact that our server doesn;t have dedicated IP
In which in some circumstances, the players may be connected to another server.
"

We've taken that to mean "Unless the player is directly connected to 'play.sunrisecity.uk:2260', they will not always be connected to the correct server". Is that incorrect?

2022-08-28 12:14 UTC, JustSkeppYT commented
> We've taken that to mean "Unless the player is directly connected to 'play.sunrisecity.uk:2260', they will not always be connected to the correct server". Is that incorrect?

That is correct.

2022-08-28 12:17 UTC, JustSkeppYT commented
Although it should be fixed after contacting the host and the chance of being connected to that server is extremely low to none.

2022-08-28 15:33 UTC, JustSkeppYT commented
I tried to connect with port :25565 and it worked, not really sure what's wrogn with that.

2022-08-30 14:41 UTC, JustSkeppYT commented
@itsJordan Any updates?

2022-08-30 19:14 UTC, itsJordan commented
> @itsJordan Any updates?

Can you confirm that all connections to 'play.sunrisecity.uk' will route players to the correct server?

2022-08-30 21:19 UTC, JustSkeppYT commented
> Can you confirm that all connections to 'play.sunrisecity.uk' will route players to the correct server?

According to the person who owns/setups the domain+cloudflare, for the past months it has never redirected us to any other server and works perfectly fine redirecting us to the correct IP. 'play.sunrisecity.uk' has been used for the past months without anything happening.

2022-08-30 21:23 UTC, itsJordan commented on servers/sunrisecity/metadata.json
> +    "primaryAddress": "play.sunrisecity.uk:2260",
```suggestion
    "primaryAddress": "play.sunrisecity.uk",
```

2022-08-30 21:25 UTC, itsJordan approved these changes

2022-08-30 21:25 UTC, merged