Added lookcraft
LunarClient/ServerMappings pull request #497
Opened 2022-09-09 05:13 UTC by zBenjx

Added logo and metadata

### General:
* [x] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated metadata.json`)*
* [x] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [x ] Folder with appropriate name has been created / updated (must not include any non-alpha characters or whitespace).
* [x] No changes were made to the file's formatting (4 spaces per tab).
* [x] There are no syntax errors.
* [x] There is no pre-existing mapping matching my id (check if there is an existing folder).
* [x] My field values match your requirements.
* You can view our patterns here: [metadata.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/metadata.schema.json), or take a look below and complete the field checklist:
  - [x] `id`: a lowercase string, which should match the folder name *(ex. `myserver`)*
  - [x] `name`: a string *(ex. `MyServerPvP`)*
  - [x] `addresses`: an array with lowercase strings *(ex. `["my.server", "your-server.com"]`)*
    - You do not need to specify subdomains, Lunar Client services automatically detect them.
  - [x] `primaryAddress`: an address *(ex. `my.server`)*
  - [x] `minecraftVersions`: an array with Minecraft versions as strings *(ex. `["1.18", "1.19"]` - Must be versions supported by Lunar Client)*
  - [x] `primaryMinecraftVersion`: a Minecraft version as a string *(ex. `1.18` - Must be versions supported by Lunar Client)*
  - [] `primaryColor`: a hexademical color code that primarily distiguishes the server *(ex. `#00FFFF`)* 
  - [ ] `secondaryColor`: a hexademical color code that accompanies the `primaryColor` of the server *(ex. `#FF0000`)*
  - [ ] `primaryRegion`: the primary region where your server operates in *(ex. `NA`)*
  - [x] `regions`: a list of regions where you have servers located that service your players *(ex. `["NA", "EU", "AS"]`)*
  - [ ] `gameTypes`: a list of games that describe the content on your server, must be a max of 3 listed *(ez. `["PVP", "UHC", "HCF"]`)*

### Media:
#### Logo
* [x] My logo is a `png` file.
* [x] I have uploaded my logo to my server folder *(ex. `lunarnetwork`)* and named it `logo.png`.
* [ ] My logo has a transparent background and is square (1:1 aspect ratio).
* [x] My logo is `512` pixels in width and height.
* [ ] My logo is my own property and complies with relevant copyright/privacy laws.

#### Background
* [ ] My background is a `png` file.
* [ ] I have uploaded my background to my server folder *(ex. `lunarnetwork`)* and named it `background.png`.
* [ ] My background has an aspect ratio of 16:9.
* [ ] My background is atleast `1920` pixels in width and `1080` pixels in height (can be bigger, but must remain the same aspect ratio).
* [ ] My background contains relevant content pertaining to the server, is my own property, and complies with relevant copyright/privacy laws.
* [ ] My background doesn't contain any markings, text, or logos (unless part of a build).

2022-09-09 10:44 UTC, wi requested changes
You are missing a background.png file check the README for more info. Also under your addresses array, you don't need "play." in front of lookcraft.tk as Lunar Client will detect it.  Also are you only able to join your server on 1.8 and 1.19? You also need the following in your metadata.json:

- primaryColor
- secondaryColor
- gameTypes

2022-09-10 00:05 UTC, zBenjx commented
Updated requirements.

2022-09-10 11:15 UTC, wi requested changes
Your background.png does not meet the minimum requirements of 1920px in width and 1080px in height (it's 1920x1027). Also as previously mentioned you're only able to join your server on ONLY 1.19 and 1.8? you need to add the other versions in between them if you can join with the different versions.

2022-09-11 18:12 UTC, wi requested changes

2022-09-11 18:12 UTC, wi commented on servers/lookcraft/metadata.json
> +        "1.10",
Only versions supported by Lunar Client need to be here

2022-09-12 10:32 UTC, wi commented on servers/lookcraft/metadata.json
> +        "1.12.2",
```suggestion
1.12
```

2022-09-12 10:32 UTC, wi commented on servers/lookcraft/metadata.json
> +        "1.12.2",
```suggestion
        "1.12",
````

2022-09-12 10:32 UTC, wi commented on servers/lookcraft/metadata.json
> +        "1.16.5",
```suggestion
        "1.16",
````

2022-09-12 10:33 UTC, wi commented on servers/lookcraft/metadata.json
> +        "1.17.1",
```suggestion
        "1.17",
````

2022-09-12 10:33 UTC, wi commented on servers/lookcraft/metadata.json
> +        "1.18.1",
```suggestion
        
````

2022-09-12 10:33 UTC, wi commented on servers/lookcraft/metadata.json
> +        "1.19.2"
```suggestion
````

2022-09-12 10:35 UTC, wi submitted a review, later dismissed

2022-09-12 10:50 UTC, wi approved these changes

2022-09-12 10:51 UTC, merged