indeed
LunarClient/ServerMappings pull request #500
Opened 2022-09-10 11:40 UTC by klirman

### General:
* [ ] The pull request title is descriptive. *(ex. `Added Lunar Network`, not `Updated metadata.json`)*
* [ ] The pull request does not contain any unrelated commits.  *(ex. commits from previous pull requests)*

### Mapping Additions or Updates:
* [ ] Folder with appropriate name has been created / updated (must not include any non-alpha characters or whitespace).
* [ ] No changes were made to the file's formatting (4 spaces per tab).
* [ ] There are no syntax errors.
* [ ] There is no pre-existing mapping matching my id (check if there is an existing folder).
* [ ] My field values match your requirements.
* You can view our patterns here: [metadata.schema.json](https://github.com/LunarClient/ServerMappings/blob/master/metadata.schema.json), or take a look below and complete the field checklist:
  - [ ] `id`: a lowercase string, which should match the folder name *(ex. `myserver`)*
  - [ ] `name`: a string *(ex. `MyServerPvP`)*
  - [ ] `addresses`: an array with lowercase strings *(ex. `["my.server", "your-server.com"]`)*
    - You do not need to specify subdomains, Lunar Client services automatically detect them.
  - [ ] `primaryAddress`: an address *(ex. `my.server`)*
  - [ ] `minecraftVersions`: an array with Minecraft versions as strings *(ex. `["1.18", "1.19"]` - Must be versions supported by Lunar Client)*
  - [ ] `primaryMinecraftVersion`: a Minecraft version as a string *(ex. `1.18` - Must be versions supported by Lunar Client)*
  - [ ] `primaryColor`: a hexademical color code that primarily distiguishes the server *(ex. `#00FFFF`)* 
  - [ ] `secondaryColor`: a hexademical color code that accompanies the `primaryColor` of the server *(ex. `#FF0000`)*
  - [ ] `primaryRegion`: the primary region where your server operates in *(ex. `NA`)*
  - [ ] `regions`: a list of regions where you have servers located that service your players *(ex. `["NA", "EU", "AS"]`)*
  - [ ] `gameTypes`: a list of games that describe the content on your server, must be a max of 3 listed *(ez. `["PVP", "UHC", "HCF"]`)*

### Media:
#### Logo
* [ ] My logo is a `png` file.
* [ ] I have uploaded my logo to my server folder *(ex. `lunarnetwork`)* and named it `logo.png`.
* [ ] My logo has a transparent background and is square (1:1 aspect ratio).
* [ ] My logo is `512` pixels in width and height.
* [ ] My logo is my own property and complies with relevant copyright/privacy laws.

#### Background
* [ ] My background is a `png` file.
* [ ] I have uploaded my background to my server folder *(ex. `lunarnetwork`)* and named it `background.png`.
* [ ] My background has an aspect ratio of 16:9.
* [ ] My background is atleast `1920` pixels in width and `1080` pixels in height (can be bigger, but must remain the same aspect ratio).
* [ ] My background contains relevant content pertaining to the server, is my own property, and complies with relevant copyright/privacy laws.
* [ ] My background doesn't contain any markings, text, or logos (unless part of a build).

2022-09-10 13:26 UTC, itsJordan requested changes
Please make the following changes:
- Upload a background that represents your server
- Upload a logo that is actually for your server (this is MineHQs logo)
- Fix / validate your json formatting and add all missing fields to your metadata file

2022-09-10 14:16 UTC, klirman commented
All done.
> * Upload a background that represents your server
this represents the server perfectly fine; it's a picture from Zurich, one of the major cities of switzerland.

2022-09-12 18:15 UTC, itsJordan requested changes
Could you please upload a logo that actually represents your server and that you have the rights to use?

2022-09-13 12:18 UTC, klirman commented
It  represents the server just fine. the entire theme of this server is it being Swiss, and what better to use as a logo than the actual flag of Switzerland? nothing would represent it better.

And yes, I do have the rights to use this. 
![image](https://user-images.githubusercontent.com/54043135/189896851-548f8f12-ccb3-48e7-a046-906ab6f504fd.png)

[Source](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3663670/#:~:text=From%20an%20international%20copyright%20law,copyright%20%5B8%2C9%5D.)

2022-09-13 17:56 UTC, itsJordan requested changes
Could you please upload a version of your background that is 1920x1080

2022-09-13 17:56 UTC, itsJordan commented on servers/swisshq/metadata.json
> +        "swisshq.net",
```suggestion
        "swisshq.net"

```

2022-09-13 17:57 UTC, itsJordan commented on servers/swisshq/metadata.json
> +    "secondaryColor": "##ff0000",
```suggestion
    "secondaryColor": "#ff0000",

```

2022-09-13 17:57 UTC, itsJordan commented on servers/swisshq/metadata.json
> +        "EU",
```suggestion
        "EU"

```

2022-09-13 17:58 UTC, itsJordan commented on servers/swisshq/metadata.json
> +
```suggestion

```

2022-09-13 17:59 UTC, itsJordan commented
This will be ready to merge once a valid background is supplied.

2022-09-14 18:49 UTC, itsJordan approved these changes

2022-09-14 18:49 UTC, merged