Update servers.json
LunarClient/ServerMappings pull request #76
Opened 2021-12-11 16:37 UTC by frnacyello

2021-12-22 16:18 UTC, GrowlyX requested changes

2021-12-22 16:18 UTC, GrowlyX commented on servers.json
> +        ]
You need to add a closing bracket

2021-12-25 11:01 UTC, frnacyello commented on servers.json
> +        ]
done

2021-12-26 17:43 UTC, GrowlyX approved these changes

2021-12-26 17:45 UTC, merged