Add ImagineFun
LunarClient/ServerMappings pull request #84
Opened 2021-12-17 06:40 UTC by HelloImCamden

2021-12-21 13:06 UTC, GrowlyX requested changes

2021-12-21 13:06 UTC, GrowlyX commented on servers.json
> +            "mc.imagineeringfun.net",
You do not need to specify sub-domains

2021-12-21 13:06 UTC, GrowlyX commented on servers.json
> +       {
This bracket is incorrectly formatted

2021-12-26 01:25 UTC, HelloImCamden commented on servers.json
> +            "mc.imagineeringfun.net",
Subdomains have been removed.

2021-12-26 01:25 UTC, HelloImCamden commented on servers.json
> +       {
Updated

2021-12-26 17:39 UTC, GrowlyX approved these changes, later dismissed

2021-12-26 17:41 UTC, GrowlyX approved these changes

2021-12-26 17:42 UTC, merged