Add Kyro Network
LunarClient/ServerMappings pull request #94
Opened 2021-12-24 07:40 UTC by GleemingKnight

2021-12-25 03:51 UTC, GrowlyX requested changes

2021-12-25 03:51 UTC, GrowlyX commented on servers.json
> +        "name": "Kyro.gg",
Please make this something other than the actual domain

2021-12-27 07:27 UTC, GleemingKnight commented
Fixed.

2021-12-27 23:07 UTC, GrowlyX approved these changes

2022-01-01 13:17 UTC, GleemingKnight commented
@GrowlyX What's up with this PR?

2022-01-02 19:10 UTC, GrowlyX commented
> @GrowlyX What's up with this PR?

![image](https://user-images.githubusercontent.com/62861393/147886752-be6061b9-293c-4a1e-897b-721446a0de75.png)

2022-01-08 06:07 UTC, closed without merging